create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '學習者',
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null,
  topic text not null,
  difficulty text not null,
  total_questions integer not null check (total_questions > 0),
  correct_count integer not null check (correct_count >= 0 and correct_count <= total_questions),
  accuracy integer not null check (accuracy between 0 and 100),
  started_at timestamptz not null,
  completed_at timestamptz not null default now()
);

create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.quiz_attempts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  selected_answer text,
  correct_answer text not null,
  is_correct boolean not null
);

create table if not exists public.wrong_questions (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  last_wrong_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

alter table public.profiles enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.wrong_questions enable row level security;

create policy "Users manage their profile"
  on public.profiles for all to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Users manage their attempts"
  on public.quiz_attempts for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their answers"
  on public.quiz_answers for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their wrong questions"
  on public.wrong_questions for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
